language: node_js
node_js:
- stable

before_script:
  - npm i -g  makeshift && makeshift -r registry.npmjs.org

deploy:
  - provider: npm
    email: v7rulnik@gmail.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
      repo: kupibilet-frontend/babel-preset-kupibilet
